// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBND5t9qke-b9tGFot0zVx9-hrsbs6HB6g',
    appId: '1:485967798887:web:62e7959a0e87e8e0ec2ac2',
    messagingSenderId: '485967798887',
    projectId: 'wisata-indonesia-app-92284',
    authDomain: 'wisata-indonesia-app-92284.firebaseapp.com',
    storageBucket: 'wisata-indonesia-app-92284.firebasestorage.app',
    measurementId: 'G-E9J2SNR37Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwpVXTGqBcLqyfbqjrO0JWnBU_6uAd_cE',
    appId: '1:485967798887:android:cb8b5e2cfc0bb09bec2ac2',
    messagingSenderId: '485967798887',
    projectId: 'wisata-indonesia-app-92284',
    storageBucket: 'wisata-indonesia-app-92284.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5Jc2ENjONSB3CQ_omyDUghn3RKf_XSgw',
    appId: '1:485967798887:ios:83b663aa5efae97dec2ac2',
    messagingSenderId: '485967798887',
    projectId: 'wisata-indonesia-app-92284',
    storageBucket: 'wisata-indonesia-app-92284.firebasestorage.app',
    iosBundleId: 'com.example.wisataApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5Jc2ENjONSB3CQ_omyDUghn3RKf_XSgw',
    appId: '1:485967798887:ios:83b663aa5efae97dec2ac2',
    messagingSenderId: '485967798887',
    projectId: 'wisata-indonesia-app-92284',
    storageBucket: 'wisata-indonesia-app-92284.firebasestorage.app',
    iosBundleId: 'com.example.wisataApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBND5t9qke-b9tGFot0zVx9-hrsbs6HB6g',
    appId: '1:485967798887:web:ee65d92cd8b58efcec2ac2',
    messagingSenderId: '485967798887',
    projectId: 'wisata-indonesia-app-92284',
    authDomain: 'wisata-indonesia-app-92284.firebaseapp.com',
    storageBucket: 'wisata-indonesia-app-92284.firebasestorage.app',
    measurementId: 'G-SHNKHKV03H',
  );
}
